name: KyberEagle
favicon: null
layout_spectrum: 0.40287532890215516
typography_spectrum: 0.7327825042884797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.004901902284473181
  lightness: 0.5138259110972285
  saturation: 0.2564217704348266
  rhythmicContrast: 0.19007765175774693
purpose: []
